# espkyogate - ESPHome custom component for Bentel KYO alarms (https://github.com/lorenzo-deluca/espkyogate)
# 2025 Lorenzo De Luca (me@lorenzodeluca.dev)
# Configuration for Bentel Kyo32G on Wemos D1 Mini (ESP8266)

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]

esp8266:
  board: d1_mini
  restore_from_flash: true

esphome:
  name: espkyogate
  comment: Bentel KYO alarm serial bridge
  includes:
    - components/bentel-kyo/bentel_kyo32.h

uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

captive_portal:

logger:
  level: INFO
  baud_rate: 0
  logs:
    component: ERROR

api:
  encryption:
    key: !secret api_encryption_key
  custom_services: true
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: !secret ota_password

switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_batteria_bassa,
        &kyo32->allarme_area[0],
        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],
        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_parziale_area[0],
        &kyo32->disinserita_area[0]
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Alarme Communication centrale"
      - id: stato_sirena
        name: "Alarme Etat sirene"
      - id: warn_batteria_bassa
        name: "Alarme Batterie faible"
      - id: allarme_area_1
        name: "Alarme generale"
      - id: kyo_zone1
        name: "Alarme Cuisine"
        device_class: door
      - id: kyo_zone2
        name: "Alarme Entree"
        device_class: door
      - id: kyo_zone3
        name: "Alarme Couloir"
        device_class: motion
      - id: kyo_zone4
        name: "Alarme Salon"
        device_class: motion
      - id: arm_total_area_1
        name: "Alarme Armement total"
      - id: arm_partial_area_1
        name: "Alarme Armement partiel"
      - id: disarmed_area_1
        name: "Alarme Desarme"

sensor:
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "WiFi Signal"

text_sensor:
  - platform: version
    name: "ESPHome Version"
